image: golang:1.23

stages:
  - test

format-check:
  stage: test
  script:
    - go fmt $(go list ./...)
    - if [ -n "$(git status --porcelain)" ]; then echo "Code is not formatted"; exit 1; fi

unit-tests:
  stage: test
  script:
    - go test -v ./...
