-- select * from items
-- where id = 1;
-- insert into items (name, description, price, stock)
-- values ('Coffee Mug', 'Xsolla branded coffee mug', 999, 5);
-- explain select * from items
-- order by id desc
-- update items set stock=4
-- where id=9;
-- delete from items
-- where id = 9;
-- select i.description, oi.quantity from order_items as oi
-- left join items as i
-- on oi.item_id=i.id
-- select *
-- from orders;
-- SELECT n.nspname as schema_name,
--   c.relname as table_name
-- FROM pg_catalog.pg_class c
--   JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
-- WHERE c.relname = 'orders';
-- SET search_path TO public;
-- INSERT INTO orders (id, user_id, total, status, created_at)
-- VALUES (1, 1, 150.00, 'processing', CURRENT_TIMESTAMP);
-- DELETE FROM carts
-- WHERE user_id = 5;
-- INSERT INTO carts (id, user_id, item_id, quantity)
-- VALUES (1, 5, 2, 3);
-- select *
-- from carts;
-- select *
-- from orders;
-- INSERT INTO orders (id, user_id, total, status, created_at)
-- VALUES (2, 5, 200.00, 'processing', CURRENT_TIMESTAMP);
-- INSERT INTO orders (id, user_id, total, status, created_at)
-- VALUES (4, 5, 30.00, 'processing', CURRENT_TIMESTAMP);
-- select *
-- from users;
-- SELECT id FROM items;
-- DELETE FROM carts
-- WHERE user_id = 5;
-- SELECT *
-- FROM inventory;
-- INSERT INTO products (sku, name_en, name_cn, price_usd, price_myr, purchase_limit)
-- VALUES ('test_item', 'Test Item', 'Test Item', 9.99, 44.95, 10);
-- SELECT *
-- FROM cart_items;
SELECT *
FROM user_inventory;