version: '3.8'

services:
  # Changed name to match what your Go code is looking for
  xsolla-gamestore-db: 
    image: postgres:17-alpine
    container_name: xsolla-gamestore-db
    environment:
      POSTGRES_USER: alanis
      POSTGRES_PASSWORD: testing12345
      POSTGRES_DB: gamestore_db
    ports:
      - "5434:5432" # Outer door 5434 (for you), Inner door 5432 (for Go)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: checkout_api
    ports:
      - "8080:8080" # Match this to your ngrok port!
    environment:
      - DATABASE_URL=postgres://alanis:testing12345@xsolla-gamestore-db:5432/gamestore_db?sslmode=disable
    depends_on:
      - xsolla-gamestore-db

volumes:
  postgres_data: