BEGIN;
CREATE TABLE inventory (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  sku VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMIT;